/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmenitiesList: typeof import('./src/components/homestay/AmenitiesList.vue')['default']
    AmenitySelector: typeof import('./src/components/AmenitySelector.vue')['default']
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AuthGuard: typeof import('./src/components/common/AuthGuard.vue')['default']
    AvatarUpload: typeof import('./src/components/AvatarUpload.vue')['default']
    BookingCard: typeof import('./src/components/homestay/BookingCard.vue')['default']
    CustomIcons: typeof import('./src/components/CustomIcons.vue')['default']
    FeaturesList: typeof import('./src/components/homestay/FeaturesList.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    HomestayCard: typeof import('./src/components/homestay/HomestayCard.vue')['default']
    HomestaySection: typeof import('./src/components/homestay/HomestaySection.vue')['default']
    HostInfo: typeof import('./src/components/homestay/HostInfo.vue')['default']
    ImageGallery: typeof import('./src/components/homestay/ImageGallery.vue')['default']
    LocationInfo: typeof import('./src/components/homestay/LocationInfo.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    NotificationBell: typeof import('./src/components/NotificationBell.vue')['default']
    OrderTimeoutIndicator: typeof import('./src/components/order/OrderTimeoutIndicator.vue')['default']
    PersonalizedRecommendations: typeof import('./src/components/homestay/PersonalizedRecommendations.vue')['default']
    PopularHomestays: typeof import('./src/components/homestay/PopularHomestays.vue')['default']
    PropertyTypeSelector: typeof import('./src/components/PropertyTypeSelector.vue')['default']
    RecommendedHomestays: typeof import('./src/components/homestay/RecommendedHomestays.vue')['default']
    ReviewEditModal: typeof import('./src/components/ReviewEditModal.vue')['default']
    ReviewForm: typeof import('./src/components/ReviewForm.vue')['default']
    ReviewsSection: typeof import('./src/components/homestay/ReviewsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchExperience: typeof import('./src/components/SearchExperience.vue')['default']
    SearchResults: typeof import('./src/components/homestay/SearchResults.vue')['default']
    SearchSuggestions: typeof import('./src/components/SearchSuggestions.vue')['default']
  }
}
